spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: false
  jpa:
    database-platform: mysql
    open-in-view: false
    show-sql: false
  thymeleaf:
    cache: true
    prefix: file:web-front/templates/
  messages:
    basename: i18n/messages
    encoding: UTF-8
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} - %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%logger#%M [L.%L]){cyan} %clr(:){faint} %m%n%wEx'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} --- %p --- [%t] %logger --- %m%n%wEx'
  level:
    root: warn